[project]
name = "darukaa-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Md Zeeshan Ali", email = "sszeeshu@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
darukaa-assignment = "darukaa_assignment:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
